### ISSUE TITLE
Better virtualization tools, provisioning

### ISSUE THREAD

**Issue by damouse** [ParadropLabs/Paradrop#7]
Can create/download new images with identity and security information embedded. Can spin them up quickly and painlessly, networking and configuration handled automatically through Vagrant or Virtualbox. VM tools are cross-platform.

**Comment by nphyatt** [comment]
# Proposed Provisioning Protocol

* User starts process by calling `paradrop create router foo` command
* pdtools downloads latest snappy image from canonical and stores it locally in the .paradrop folder
* pdtools gets a checksum of the image
* pdtools sends request to backend for provisioning of new router and sends checksum
* backend receives request and launches a process which does the following:
   1. compares checksum to known checksums for versions of the snappy image
   2. chooses the corresponding snappy image based on the checksum
   3. opens a snappy image with Paradrop and Docker installed which corresponds to the right version
   4. drops in the provisioning keys
   5. drops in name of the router
   6. disables password based ssh
   7. changes root password on the image
   8. gets the binary diff of the new image and the original snappy image
   9. Stores the information about the new router(keys, name, etc.) and its owner in the DB
* backend then returns the binary diff to pdtools
* pdtools applies the binary diff to the snappy image and  voila we have a fully provisioned Paradrop router

## Notes
* Allow for a flag which will cache the snappy image locally and allow for faster creating of multiple routers

**Comment by nphyatt** [comment]
# Diff Analysis

## 1KB blocks using hashing and pickle
* from vanilla-snappy -> snappy with install_deps (Docker, hostapd, dnsmasq)
   * 80 seconds and 400MB changes.pk
* from install_deps -> full_install.img with Paradrop
   * 50 seconds and 131MB changes.pk
*from vanilla -> full install.img
   * 43 seconds and 313MB

**Comment by nphyatt** [comment]
# Provisioning Protocal v2

1. user calls `pdtools create router foo'
2. pdtools makes request to backend for provisioned router
3. backend then:
   * opens image
   * drops in provisioning keys
   * drops in name of router
   * disables password based ssh
   * changes root pass on image
   * closes image and compresses (using native python library)
   * uploads image to S3 with 24 hour expiration
   * sends user an email once their image is uploaded with 1 time link to file for download
   * stores info about about the new router(keys, name, etc.) and its owner in the DB
4. User clicks link to download file
5. User runs `pdtools provision router path/to/zip/file` 
6. pdtools unzips image and puts it at .paradrop/routers/router-name.img
7. `pdtools up`  launces router in vm
